version: 0.2

phases:
  install:
    commands:
      - echo Set-up..
      - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - wget -q -O - https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - sudo apt-get update
      - echo Installing NGINX
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Build started on 'date'
      - cp /var/www/html/index*.html /var/www/html/index.html
  post_build:
    commands:
      - echo Configuring NGINX - variables
      - echo name- CONTAINER_NAME
      - echo imageUri- $REPOSITORY_URI
      - printf '[{"name":"$CONTAINER_NAME","imageUri":"$REPOSITORY_URI"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - /var/www/html/index.html
